Added Home Page Design
AOSP-NIT-Surat/Bookstore-Frontend-web pull request #8
Opened 2021-10-03 08:52 UTC by Hetu1107

closes https://github.com/AOSP-NIT-Surat/Bookstore-Frontend-web/issues/5

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug Fix
- [x] New Feature
- [x] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe below:

**Checklist**
- [ ] I have read the **[CONTRIBUTING Guidelines](https://github.com/AOSP-NIT-Surat/Bookstore-Frontend-web/blob/main/.github/CONTRIBUTING.md)**.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

**Any Other information:**

2021-10-04 11:02 UTC, astonizer commented
@Hetu1107 please resolve all the conflicts

2021-10-04 12:26 UTC, astonizer requested changes
Few things to be checked out before this pr gets merged.
- Shift your code from `src/component/Home.js` to `src/pages/Home.js`.
- Your css files should go under `src/styles/` directory.
- As for the slider part, I would suggest to go with either of the below two
           1. As you've used a custom slider, it's always a good practice to include some form of               documentation as to what every function or piece of code is doing.
           2. Or you can use a pre-built bootstrap slider or carousel.

2021-10-04 13:51 UTC, Hetu1107 commented
@astonizer i haved changed file derectory and also added react bootstrap slide please check that agin

2021-10-05 06:23 UTC, astonizer approved these changes

2021-10-05 06:23 UTC, merged